#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

deskey=$(ynh_string_random --length=24)
ynh_app_setting_set --key=deskey --value=$deskey

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chown -R $app:www-data "$install_dir"
chmod -R 750 "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_phpfpm

#=================================================
# CONFIGURE AENERIA
#=================================================
ynh_script_progression "Configuring $app..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

chmod 600 "$install_dir/.env"

#=================================================
# INSTALL AENERIA
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir
  ynh_exec_as_app php$php_version bin/console aeneria:install "$app" -n
  # Create admin user
  mail=$(ynh_user_get_info --username="$admin" --key='mail')
  ynh_exec_as_app php$php_version bin/console aeneria:user:add "$mail" "$(ynh_string_random)" -n
  ynh_exec_as_app php$php_version bin/console aeneria:user:grant "$mail"
popd

#=================================================
# SET UP CRON JOB
#=================================================
ynh_script_progression "Setuping a cron..."

# Generate random running schedule, and save $hour and $minutes as app parameters
generate_random_minutes_hour

ynh_config_add --template="aeneria.cron" --destination="/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
